{{- if and 
  (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "ipaddresspools.metallb.io") 
  (lookup "v1" "Namespace" "" "metallb-system")  
}}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: {{ .Release.Name }}-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - {{ .Values.metallbIpPool }}
{{- end }}
