# chart-setting
metallbIpPool: 192.168.220.41/32

# common
namespace: test-namespace

labels:
  app: nginx

# Deployment
replicas: 3

images: 
  nginx: nginx:latest

ports:
  nginx: 
    containerPort: 80
    servicePort: 80
